export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const PRODUCT_DETAIL = 'PRODUCT_DETAIL';
export const UPDATE_AMOUNT = 'UPDATE_AMOUNT';
export const PRODUCT_RELATIVE = 'PRODUCT_RELATIVE';
export const MAIN_SLIDER = 'MAIN_SLIDER';